import localFont from "next/font/local";
import "./globals.css";

import styles from "./page.module.css";

import Footer from "@/components/Footer/Footer";
import Header from "@/components/header/Header";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.mainContainer}>
          <div className={styles.sidebarContainer}>
            <img className={styles.appLogo} src="static/images/barclays.png"></img>
            <div className={styles.menuList}>
              <div className={styles.menu}>Home</div>
              <div className={styles.active}>My Machines</div>
            </div>
          </div>
          <div className={styles.pageContainer}>
            <div className={styles.headerContainer}>
              <Header />
            </div>
            <div className={styles.contextualContainer}>
              <div className={styles.contextualWrapper}>
                {children}
              </div>
              <div className={styles.footerContainer}>
                <Footer />
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}